/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPluginsRouteImport } from './routes/api.plugins'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsOwnerRepoRouteImport } from './routes/plugins.$owner.$repo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsRoute = ApiPluginsRouteImport.update({
  id: '/api/plugins',
  path: '/api/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsOwnerRepoRoute = PluginsOwnerRepoRouteImport.update({
  id: '/plugins/$owner/$repo',
  path: '/plugins/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/plugins': typeof ApiPluginsRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$owner/$repo': typeof PluginsOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/plugins': typeof ApiPluginsRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$owner/$repo': typeof PluginsOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/plugins': typeof ApiPluginsRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$owner/$repo': typeof PluginsOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/plugins'
    | '/plugins/'
    | '/plugins/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/plugins'
    | '/plugins'
    | '/plugins/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/plugins'
    | '/plugins/'
    | '/plugins/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPluginsRoute: typeof ApiPluginsRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsOwnerRepoRoute: typeof PluginsOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins': {
      id: '/api/plugins'
      path: '/api/plugins'
      fullPath: '/api/plugins'
      preLoaderRoute: typeof ApiPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$owner/$repo': {
      id: '/plugins/$owner/$repo'
      path: '/plugins/$owner/$repo'
      fullPath: '/plugins/$owner/$repo'
      preLoaderRoute: typeof PluginsOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPluginsRoute: ApiPluginsRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsOwnerRepoRoute: PluginsOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
